const icons = [
	// Allgemein
	{
		name: "^circ",
		command: "^\\circ",
		category: "Allgemein",
		path: "/theme/icons/symbols-svg/allgemein/^circ.svg",
	},
	{
		name: "approx",
		command: "\\approx",
		category: "Allgemein",
		path: "/theme/icons/symbols-svg/allgemein/approx.svg",
	},
	{
		name: "cdot",
		command: "\\cdot",
		category: "Allgemein",
		path: "/theme/icons/symbols-svg/allgemein/cdot.svg",
	},
	{
		name: "cdots",
		command: "\\cdots",
		category: "Allgemein",
		path: "/theme/icons/symbols-svg/allgemein/cdots.svg",
	},
	{
		name: "dfrac_d_f",
		command: "\\dfrac{}{}",
		category: "Allgemein",
		path: "/theme/icons/symbols-svg/allgemein/dfrac_d_f.svg",
	},
	{
		name: "frac_a_b",
		command: "\\frac{}{}",
		category: "Allgemein",
		path: "/theme/icons/symbols-svg/allgemein/frac_a_b.svg",
	},
	{
		name: "pm",
		command: "\\pm",
		category: "Allgemein",
		path: "/theme/icons/symbols-svg/allgemein/pm.svg",
	},
	{
		name: "sqrt",
		command: "\\sqrt{}",
		category: "Allgemein",
		path: "/theme/icons/symbols-svg/allgemein/sqrt.svg",
	},
	// Griechisch
	{
		name: "alpha",
		command: "\\alpha",
		category: "Griechisch",
		path: "/theme/icons/symbols-svg/griechisch/alpha.svg",
	},
	{
		name: "beta",
		command: "\\beta",
		category: "Griechisch",
		path: "/theme/icons/symbols-svg/griechisch/beta.svg",
	},
	{
		name: "delta",
		command: "\\delta",
		category: "Griechisch",
		path: "/theme/icons/symbols-svg/griechisch/delta.svg",
	},
	{
		name: "epsilon",
		command: "\\epsilon",
		category: "Griechisch",
		path: "/theme/icons/symbols-svg/griechisch/epsilon.svg",
	},
	{
		name: "gamma",
		command: "\\gamma",
		category: "Griechisch",
		path: "/theme/icons/symbols-svg/griechisch/gamma.svg",
	},
	{
		name: "lambda",
		command: "\\lambda",
		category: "Griechisch",
		path: "/theme/icons/symbols-svg/griechisch/lambda.svg",
	},
	{
		name: "mu",
		command: "\\mu",
		category: "Griechisch",
		path: "/theme/icons/symbols-svg/griechisch/mu.svg",
	},
	{
		name: "phi",
		command: "\\phi",
		category: "Griechisch",
		path: "/theme/icons/symbols-svg/griechisch/phi.svg",
	},
	{
		name: "pi",
		command: "\\pi",
		category: "Griechisch",
		path: "/theme/icons/symbols-svg/griechisch/pi.svg",
	},
	{
		name: "sigma",
		command: "\\sigma",
		category: "Griechisch",
		path: "/theme/icons/symbols-svg/griechisch/sigma.svg",
	},
	{
		name: "tau",
		command: "\\tau",
		category: "Griechisch",
		path: "/theme/icons/symbols-svg/griechisch/tau.svg",
	},
	{
		name: "theta",
		command: "\\theta",
		category: "Griechisch",
		path: "/theme/icons/symbols-svg/griechisch/theta.svg",
	},
	{
		name: "zeta",
		command: "\\zeta",
		category: "Griechisch",
		path: "/theme/icons/symbols-svg/griechisch/zeta.svg",
	},
	// Pfeile
	{
		name: "leftarrow-1",
		command: "\\Leftarrow",
		category: "Pfeile",
		path: "/theme/icons/symbols-svg/pfeile/Leftarrow-1.svg",
	},
	{
		name: "leftarrow",
		command: "\\leftarrow",
		category: "Pfeile",
		path: "/theme/icons/symbols-svg/pfeile/leftarrow.svg",
	},
	{
		name: "Leftrightarrow",
		command: "\\Leftrightarrow",
		category: "Pfeile",
		path: "/theme/icons/symbols-svg/pfeile/Leftrightarrow.svg",
	},
	{
		name: "Rightarrow-1",
		command: "\\Rightarrow",
		category: "Pfeile",
		path: "/theme/icons/symbols-svg/pfeile/Rightarrow-1.svg",
	},
	{
		name: "rightarrow",
		command: "\\rightarrow",
		category: "Pfeile",
		path: "/theme/icons/symbols-svg/pfeile/rightarrow.svg",
	},
	{
		name: "xleftarrow",
		command: "\\xleftarrow{}",
		category: "Pfeile",
		path: "/theme/icons/symbols-svg/pfeile/xleftarrow.svg",
	},
	{
		name: "xrightarrow",
		command: "\\xrightarrow{}",
		category: "Pfeile",
		path: "/theme/icons/symbols-svg/pfeile/xrightarrow.svg",
	},
	// Speziell
	{
		name: "overline_oben",
		command: "\\overline{}",
		category: "Speziell",
		path: "/theme/icons/symbols-svg/speziell/overline_oben.svg",
	},
	{
		name: "text_(left-right)",
		command: "\\left(ight) \\right(ight)",
		category: "Speziell",
		path: "/theme/icons/symbols-svg/speziell/text_(left-right).svg",
	},
	{
		name: "text_align",
		command: "\\begin{aligned} \\end{aligned}",
		category: "Speziell",
		path: "/theme/icons/symbols-svg/speziell/text_align.svg",
	},
	{
		name: "text_array",
		command: "\\begin{array}{r} \\end{array}",
		category: "Speziell",
		path: "/theme/icons/symbols-svg/speziell/text_array.svg",
	},
	{
		name: "text_left-right",
		command: "\\left(ight) \\right(ight)",
		category: "Speziell",
		path: "/theme/icons/symbols-svg/speziell/text_left-right.svg",
	},
	{
		name: "text_text",
		command: "\\text{}",
		category: "Speziell",
		path: "/theme/icons/symbols-svg/speziell/text_text.svg",
	},
	{
		name: "textcolor_red_ro",
		command: "\\textcolor{red}{}",
		category: "Speziell",
		path: "/theme/icons/symbols-svg/speziell/textcolor_red_ro.svg",
	},
	{
		name: "underbrace_Klamm",
		command: "\\underbrace{}",
		category: "Speziell",
		path: "/theme/icons/symbols-svg/speziell/underbrace_Klamm.svg",
	},
	{
		name: "underbrace_unten",
		command: "\\underline{}",
		category: "Speziell",
		path: "/theme/icons/symbols-svg/speziell/underline_unten.svg",
	},
	// Symbole
	{
		name: "cap",
		command: "\\cap",
		category: "Symbole",
		path: "/theme/icons/symbols-svg/symbole/cap.svg",
	},
	{
		name: "cup",
		command: "\\cup",
		category: "Symbole",
		path: "/theme/icons/symbols-svg/symbole/cup.svg",
	},
	{
		name: "in",
		command: "\\in",
		category: "Symbole",
		path: "/theme/icons/symbols-svg/symbole/in.svg",
	},
	{
		name: "int_limits_a^b",
		command: "\\int\\limits_{a}^{b}",
		category: "Symbole",
		path: "/theme/icons/symbols-svg/symbole/int_limits_a^b.svg",
	},
	{
		name: "not_perp",
		command: "\\not_perp",
		category: "Symbole",
		path: "/theme/icons/symbols-svg/symbole/not_perp.svg",
	},
	{
		name: "nparallel",
		command: "\\nparallel",
		category: "Symbole",
		path: "/theme/icons/symbols-svg/symbole/nparallel.svg",
	},
	{
		name: "parallel",
		command: "\\parallel",
		category: "Symbole",
		path: "/theme/icons/symbols-svg/symbole/parallel.svg",
	},
	{
		name: "perp",
		command: "\\perp",
		category: "Symbole",
		path: "/theme/icons/symbols-svg/symbole/perp.svg",
	},
	// Trigonometrie
	{
		name: "cos",
		command: "\\cos{}",
		category: "Trigonometrie",
		path: "/theme/icons/symbols-svg/trigonometrie/cos.svg",
	},
	{
		name: "cos^-1",
		command: "\\cos^{-1}",
		category: "Trigonometrie",
		path: "/theme/icons/symbols-svg/trigonometrie/cos^-1.svg",
	},
	{
		name: "sin",
		command: "\\sin{}",
		category: "Trigonometrie",
		path: "/theme/icons/symbols-svg/trigonometrie/sin.svg",
	},
	{
		name: "sin^-1",
		command: "\\sin^{-1}",
		category: "Trigonometrie",
		path: "/theme/icons/symbols-svg/trigonometrie/sin^-1.svg",
	},
	{
		name: "tan",
		command: "\\tan{}",
		category: "Trigonometrie",
		path: "/theme/icons/symbols-svg/trigonometrie/tan.svg",
	},
	{
		name: "tan^-1",
		command: "\\tan^{-1}",
		category: "Trigonometrie",
		path: "/theme/icons/symbols-svg/trigonometrie/tan^-1.svg",
	},
];

export default icons;
