name: tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: project - install
        run: yarn --frozen-lockfile
      - name: lint
        run: yarn lint

      - name: test
        run: xvfb-run yarn test --coverage --source-map --verbose || exit 1
